export const CHANGE_ORDER_LIST = 'CHANGE_ORDER_LIST';
export const DELETE_ORDER = 'DELETE_ORDER';
export const CHANGE_RECOMMEND_LIST = 'CHANGE_RECOMMEND_LIST'
export const CHANGE_ENTER_LOADING = 'CHANGE_ENTER_LOADING';
export const UPDATE_ORDER_LIST = 'UPDATE_ORDER_LIST'
export const ADD_ORDER = 'ADD_ORDER';