export const CHANGE_SELECTED_GOODS = 'CHANGE_SELECTED_GOODS'
export const CHANGE_SELECT_ALL = 'CHANGE_SELECT_ALL'
export const CHANGE_TOTLE = 'CHANGE_TOTLE';
export const DELETE_GOODS = 'DELETE_GOODS';
export const CHANGE_GOODS_ACOUNT = 'CHANGE_GOODS_ACOUNT';
export const CHANGE_RECOMMEND_LIST = 'CHANGE_RECOMMEND_LIST';
export const CHANGE_ENTER_LOADING = 'CHANGE_ENTER_LOADING';
export const CHANGE_CART_LIST = 'CHANGE_CART_LIST'